/*
 * declaration.c
 *
 * Read one line of input with fgets into a fixed buffer, then scan
 * the buffer until the null terminator is reached. Newline characters
 * are replaced with a space and each character is printed with its
 * index position.
 */

// top only documentation was generated by : RAPTOR MINI 
// every other line of code was written by : Rabiul Awal Jihad  [me :) ]

#include<stdio.h>
#include<stdlib.h>


int main(){
    
    char line[100];
    fgets(line,100,stdin);
    for(int i=0;i<100;i++){
        if(line[i]=='\n') line[i]=' ';
        else if (line[i]=='\0') break;
        else printf("char c: %c , pos= %d \n",line[i],i);

    }
    
}