/*
 * strtok.c
 *
 * Simple tokenizer example for shell-style input parsing.
 *
 * Reads a line from stdin into a mutable buffer, then splits the
 * line into tokens using whitespace delimiters. Each token is printed
 * on its own line.
 *
 * This demonstrates how strtok() modifies the input buffer in place
 * and how to iterate through tokens using strtok(NULL, ...).
 */

 // top only documentation was generated by : RAPTOR MINI 
// every other line of code was written by : Rabiul Awal Jihad ]


#include<stdio.h>
#include<stdlib.h>
#include<string.h>

int main(){
    char line[100];
    char *arguments[10];
    fgets(line,100,stdin);
    const char delimitter[]=" \t\n";

    char* token=strtok(line,delimitter);
    int n=0;
    while(token){
        arguments[n++]=token;
        token=strtok(NULL,delimitter);
    }
    arguments[n++]=NULL;
    for (int i=0;i<n;i++){
        printf("%s \n",arguments[i]);
    }
}